# Starts the whole thing: the OpenWA gateway and the bridge.
#
#   .\start.ps1
#
# Then open http://localhost:2785, start the session once and scan the QR.
# After that, POST {"id": "...", "msg": "..."} to http://localhost:8000/send

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$repo = Join-Path $root "repo"
$bridge = Join-Path $root "bridge"
$python = Join-Path $bridge ".venv\Scripts\python.exe"

$env:Path = "C:\Program Files\nodejs;C:\Program Files\Git\usr\bin;" + $env:Path

# ---- first run: write the two .env files ---------------------------------
# They are gitignored (they hold secrets), so a fresh clone has neither. They
# also share a secret: the bridge authenticates to the gateway with the key the
# gateway is configured to accept. Generating both together is what keeps that
# pair in step - setting them by hand is where a fresh install usually breaks.

$repoEnv = Join-Path $repo ".env"
$bridgeEnv = Join-Path $bridge ".env"

if (-not (Test-Path $repoEnv) -or -not (Test-Path $bridgeEnv)) {
    Write-Host ""
    Write-Host "  First run - setting up configuration." -ForegroundColor Cyan
    Write-Host ""

    function New-Secret([int]$bytes) {
        $b = New-Object byte[] $bytes
        [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
        return ($b | ForEach-Object { $_.ToString("x2") }) -join ""
    }

    $gatewayKey = New-Secret 32   # shared: API_MASTER_KEY <-> OPENWA_API_KEY
    $bridgeKey = New-Secret 24    # what Postman sends to /send
    $eventsSecret = New-Secret 24 # signs gateway -> bridge deliveries

    # Chrome is required: dependencies install without Puppeteer's own copy.
    $chrome = @(
        "C:\Program Files\Google\Chrome\Application\chrome.exe",
        "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
        "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe"
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1
    if (-not $chrome) {
        Write-Error "Google Chrome not found. Install it, then run this again."
    }
    Write-Host "  Chrome:  $chrome" -ForegroundColor DarkGray

    $mongo = Read-Host "  MongoDB URI [mongodb://localhost:27017]"
    if (-not $mongo) { $mongo = "mongodb://localhost:27017" }
    $pollUrl = Read-Host "  Queue URL to poll, blank to skip (e.g. https://<worker>.workers.dev/wam)"
    $pollToken = ""
    if ($pollUrl) { $pollToken = Read-Host "  Bearer token for that URL" }

    if (-not (Test-Path $repoEnv)) {
@"
# OpenWA gateway - local configuration, generated by start.ps1
PORT=2785
NODE_ENV=production
AUTO_START_SESSIONS=true

DATABASE_TYPE=sqlite
DATABASE_NAME=./data/openwa.sqlite
DATABASE_SYNCHRONIZE=true
DATABASE_LOGGING=false

ENGINE_TYPE=whatsapp-web.js
SESSION_DATA_PATH=./data/sessions
PUPPETEER_HEADLESS=true
PUPPETEER_ARGS=--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage
PUPPETEER_EXECUTABLE_PATH=$chrome

WEBHOOK_TIMEOUT=10000
WEBHOOK_RETRY_DELAY=5000
WEBHOOK_SHUTDOWN_DRAIN_MS=15000
# The bridge listens on loopback, which the SSRF guard blocks by default.
# Without this allowlist the gateway cannot deliver events to it at all.
SSRF_ALLOWED_HOSTS=localhost,127.0.0.1

STORAGE_TYPE=local
STORAGE_LOCAL_PATH=./data/media

REDIS_ENABLED=false
QUEUE_ENABLED=false
CACHE_ENABLED=false

API_MASTER_KEY=$gatewayKey
CSP_UPGRADE_INSECURE_REQUESTS=false
"@ | Set-Content -Path $repoEnv -Encoding utf8
        Write-Host "  wrote repo\.env" -ForegroundColor Green
    }

    if (-not (Test-Path $bridgeEnv)) {
@"
# OpenWA bridge - generated by start.ps1
BRIDGE_HOST=0.0.0.0
BRIDGE_PORT=8000
BRIDGE_API_KEY=$bridgeKey
LOG_LEVEL=info

MONGO_URI=$mongo
MONGO_DB=openwa
MONGO_COLLECTION=messages
MONGO_EVENTS_COLLECTION=events
STORE_RAW_EVENTS=true

# Poll this URL for messages to send. Empty disables polling.
POLL_URL=$pollUrl
POLL_TOKEN=$pollToken
POLL_INTERVAL=3
POLL_TIMEOUT=15

OPENWA_BASE_URL=http://127.0.0.1:2785
OPENWA_API_KEY=$gatewayKey
OPENWA_SESSION_NAME=default
OPENWA_TIMEOUT=30

EVENTS_PATH=/webhooks/openwa
EVENTS_SECRET=$eventsSecret
EVENTS_URL=http://127.0.0.1:8000/webhooks/openwa
EVENTS_AUTO_REGISTER=true
EVENTS_SUBSCRIBE=message.received,message.sent,message.ack,message.failed,message.revoked,message.edited,session.status

DEFAULT_COUNTRY_CODE=
"@ | Set-Content -Path $bridgeEnv -Encoding utf8
        Write-Host "  wrote bridge\.env" -ForegroundColor Green
    }

    Write-Host ""
    Write-Host "  Your key for sending messages (Authorization: Bearer ...):" -ForegroundColor Cyan
    Write-Host "  $bridgeKey" -ForegroundColor Yellow
    Write-Host "  Also saved as BRIDGE_API_KEY in bridge\.env" -ForegroundColor DarkGray
    Write-Host ""
}

# ---- first run: install and build ----------------------------------------

if (-not (Test-Path (Join-Path $repo "node_modules"))) {
    Write-Host "Installing gateway dependencies (first run, a few minutes)..." -ForegroundColor Cyan
    Push-Location $repo
    # --ignore-scripts is required on Windows: npm would otherwise run node-gyp
    # for better-sqlite3, which needs Visual Studio C++ Build Tools. The package
    # ships a prebuilt win32-x64 binary its loader prefers anyway. postinstall
    # is then run by hand for the upstream whatsapp-web.js/baileys patches.
    npm ci --ignore-scripts
    if ($LASTEXITCODE -ne 0) { Pop-Location; Write-Error "npm ci failed" }
    node scripts/postinstall.js
    if ($LASTEXITCODE -ne 0) { Pop-Location; Write-Error "postinstall failed" }
    Pop-Location
}

if (-not (Test-Path (Join-Path $repo "dist\main.js"))) {
    Write-Host "Building the gateway (first run only)..." -ForegroundColor Cyan
    Push-Location $repo
    npm run build
    if ($LASTEXITCODE -ne 0) { Pop-Location; Write-Error "build failed" }
    Pop-Location
}

if (-not (Test-Path (Join-Path $repo "dashboard\dist"))) {
    Write-Host "Building the dashboard (first run only)..." -ForegroundColor Cyan
    Push-Location $repo
    npm run dashboard:build
    if ($LASTEXITCODE -ne 0) { Write-Warning "dashboard build failed - the API still works, the UI will not" }
    Pop-Location
}

if (-not (Test-Path $python)) {
    Write-Host "Creating the Python environment (first run only)..." -ForegroundColor Cyan
    Push-Location $bridge
    python -m venv .venv
    & $python -m pip install --upgrade pip --quiet
    & $python -m pip install -r requirements.txt
    if ($LASTEXITCODE -ne 0) { Pop-Location; Write-Error "pip install failed" }
    Pop-Location
}

# ---- start both processes ------------------------------------------------

Write-Host "Starting the OpenWA gateway..." -ForegroundColor Cyan
Start-Process powershell -ArgumentList @(
    "-NoExit", "-Command",
    "`$host.UI.RawUI.WindowTitle='OpenWA gateway'; Set-Location '$repo'; " +
    "`$env:Path='C:\Program Files\nodejs;' + `$env:Path; node dist/main"
)

# The bridge creates the session and registers the event subscription at
# startup, so it should come up second - otherwise it just logs a warning and
# you would have to call POST /events/register yourself.
Write-Host "Waiting for the gateway to come up..." -NoNewline
$ready = $false
foreach ($attempt in 1..60) {
    Start-Sleep -Seconds 2
    try {
        Invoke-WebRequest -Uri "http://127.0.0.1:2785/api/sessions" -TimeoutSec 3 -UseBasicParsing | Out-Null
        $ready = $true
        break
    }
    catch {
        # 401 means it is up and asking for a key, which is all we need to know.
        if ($_.Exception.Response -and $_.Exception.Response.StatusCode.value__ -eq 401) {
            $ready = $true
            break
        }
        Write-Host "." -NoNewline
    }
}
Write-Host ""

if (-not $ready) {
    Write-Warning "The gateway did not answer within 2 minutes. Check its window for errors."
}

Write-Host "Starting the bridge..." -ForegroundColor Cyan
Start-Process powershell -ArgumentList @(
    "-NoExit", "-Command",
    "`$host.UI.RawUI.WindowTitle='OpenWA bridge'; Set-Location '$bridge'; " +
    "& '$python' -m app.main"
)

Start-Sleep -Seconds 4

Write-Host ""
Write-Host "  Running." -ForegroundColor Green
Write-Host ""
Write-Host "  1. Open the dashboard:  " -NoNewline; Write-Host "http://localhost:2785" -ForegroundColor Yellow
Write-Host "     Start the 'default' session and scan the QR. Once only - it is"
Write-Host "     remembered across restarts."
Write-Host ""
Write-Host "  2. Then send messages:  " -NoNewline; Write-Host "POST http://localhost:8000/send" -ForegroundColor Yellow
Write-Host "     header  X-API-Key: <BRIDGE_API_KEY from bridge\.env>"
Write-Host "     body    {`"id`": `"919876543210`", `"msg`": `"hello`"}"
Write-Host ""
Write-Host "  Check readiness any time:  curl.exe http://localhost:8000/health" -ForegroundColor DarkGray
Write-Host "  Both processes run in their own windows. Close them to stop." -ForegroundColor DarkGray
Write-Host ""
